services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: vecdb
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
